import fs from 'node:fs';
import path from 'node:path';

export const GEMINI_V3_DIR = process.env.MEDS_DATABASE_V3_EXPORT
  || '/home/indu/medsor/meds_database_v3_export';
const SOURCE_TAG = 'aistudio_curated_20261005';
const SOURCE_LABEL = 'Gemini v3 · AI Studio küratörlü';
const METADATA_DIR = process.env.MEDS_GEMINI_V3_METADATA_DIR
  || '/home/indu/medsor/meds_database/deepseek_meta_data';

type V3Question = Record<string, any>;
type V3Lecture = Record<string, any>;

let questionCache: V3Question[] | null = null;
let lectureCache: V3Lecture[] | null = null;
let thesaurusCache: Record<string, any> | null = null;

function readJsonl(file: string): any[] {
  const full = path.join(GEMINI_V3_DIR, file);
  if (!fs.existsSync(full)) return [];
  const rows: any[] = [];
  for (const line of fs.readFileSync(full, 'utf8').split(/\r?\n/)) {
    if (!line.trim()) continue;
    try { const value = JSON.parse(line); if (value && typeof value === 'object') rows.push(value); } catch { /* report is generated by validator */ }
  }
  return rows;
}

function isTagged(value: any): boolean {
  const tag = value?.curation_provenance?.tag || value?.curation_tag || value?.source_tag;
  return typeof tag === 'string' && tag === SOURCE_TAG;
}

function withSource(value: any, kind: string) {
  return { ...value, source: 'gemini_v3', sourceLabel: SOURCE_LABEL, sourceTag: SOURCE_TAG, dataKind: kind };
}

export function getGeminiV3Questions(filters: { q?: string; committeeId?: string; limit?: number; offset?: number } = {}) {
  if (!questionCache) questionCache = readJsonl('questions_curated.jsonl').filter(isTagged).map((q) => withSource(q, 'question'));
  const query = String(filters.q || '').trim().toLocaleLowerCase('tr-TR');
  const committee = String(filters.committeeId || '').replace(/\D/g, '');
  const filtered = questionCache.filter((q) => {
    if (committee && String(q.kurul || '') !== committee) return false;
    if (!query) return true;
    return [q.stem, q.ders, q.konu, ...(Object.values(q.options || {}) as string[])].join(' ').toLocaleLowerCase('tr-TR').includes(query);
  });
  const offset = Math.max(0, filters.offset || 0);
  const limit = Math.min(3000, Math.max(1, filters.limit || 20));
  return { total: filtered.length, items: filtered.slice(offset, offset + limit), source: 'gemini_v3', sourceLabel: SOURCE_LABEL };
}

export function getGeminiV3Lectures(filters: { q?: string; committeeId?: string; limit?: number } = {}) {
  if (!lectureCache) lectureCache = readJsonl('lecture_notes_master_curated.jsonl').filter(isTagged).map((n) => withSource(n, 'lecture_note'));
  const query = String(filters.q || '').trim().toLocaleLowerCase('tr-TR');
  const committee = String(filters.committeeId || '').replace(/\D/g, '');
  const filtered = lectureCache.filter((n) => {
    if (committee && String(n.kurul || '') !== committee) return false;
    return !query || [n.title, n.ders, n.markdown_path].join(' ').toLocaleLowerCase('tr-TR').includes(query);
  });
  return { total: filtered.length, items: filtered.slice(0, Math.min(100, Math.max(1, filters.limit || 50))), source: 'gemini_v3', sourceLabel: SOURCE_LABEL };
}

export function getGeminiV3Thesaurus(q?: string) {
  if (!thesaurusCache) {
    const full = path.join(GEMINI_V3_DIR, 'medical_thesaurus_expanded.json');
    thesaurusCache = fs.existsSync(full) ? JSON.parse(fs.readFileSync(full, 'utf8')) : {};
  }
  const query = String(q || '').trim().toLocaleLowerCase('tr-TR');
  const entries = Object.entries(thesaurusCache || {}).filter(([key, value]) => !query || [key, JSON.stringify(value)].join(' ').toLocaleLowerCase('tr-TR').includes(query));
  return { total: entries.length, items: entries.slice(0, 100).map(([key, value]) => withSource({ key, ...(value as any) }, 'medical_thesaurus')), source: 'gemini_v3', sourceLabel: SOURCE_LABEL, provenance: 'file_manifest_verified' };
}

export function getGeminiV3Status() {
  const files = ['questions_curated.jsonl', 'lecture_notes_master_curated.jsonl', 'medical_thesaurus_expanded.json', 'audit_rejected_questions.jsonl'];
  const exists = Object.fromEntries(files.map((file) => [file, fs.existsSync(path.join(GEMINI_V3_DIR, file))]));
  const questions = getGeminiV3Questions({ limit: 1 });
  const lectures = getGeminiV3Lectures({ limit: 1 });
  const rejected = readJsonl('audit_rejected_questions.jsonl');
  return {
    source: 'gemini_v3', sourceLabel: SOURCE_LABEL, sourceTag: SOURCE_TAG,
    root: GEMINI_V3_DIR, exists, acceptedQuestions: questions.total, acceptedLectures: lectures.total,
    rejectedQuestions: rejected.length, excludedRejectedQuestions: rejected.length,
    excludedReason: 'audit_rejected_questions.jsonl kayıtlarında zorunlu curation_provenance/source_tag bulunmuyor; mevcut veriye karıştırılmıyor.',
    immutable: true,
  };
}

function readApproved(name: string) {
  const file = path.join(METADATA_DIR, name);
  if (!fs.existsSync(file)) return { metadata: {}, items: [] };
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

export function getGeminiV3ApprovedRelations() {
  return { ...readApproved('gemini_v3_question_curriculum_relations.json'), source: 'gemini_v3', sourceLabel: SOURCE_LABEL };
}

export function getGeminiV3ApprovedSynonyms(q?: string) {
  const data = readApproved('gemini_v3_medical_synonyms.json');
  const query = String(q || '').toLocaleLowerCase('tr-TR');
  const items = Object.values(data.items || {}).filter((item: any) => !query || JSON.stringify(item).toLocaleLowerCase('tr-TR').includes(query));
  return { metadata: data.metadata, items: items.slice(0, 200), total: items.length, source: 'gemini_v3', sourceLabel: SOURCE_LABEL };
}

export function getGeminiV3LectureMarkdown(sourceId: string) {
  const lectures = getGeminiV3Lectures({ limit: 1000 }).items;
  const note = lectures.find((item) => item.source_id === sourceId);
  if (!note?.markdown_path) return null;
  const full = path.resolve(GEMINI_V3_DIR, note.markdown_path);
  const root = path.resolve(GEMINI_V3_DIR);
  if (!full.startsWith(root + path.sep) || !fs.existsSync(full)) return null;
  return { ...note, markdown: fs.readFileSync(full, 'utf8') };
}
