# -*- coding: utf-8 -*-
"""
Medical Master Taxonomy Generator
Generates comprehensive clinical entities across all major organ systems and basic sciences.
"""

def generate_master_taxonomy():
    items = []

    # 1. FARMAKOLOJİ MASTER (İlaçlar, Etki Mekanizmaları, Reseptörler, Toksisiteler)
    pharm_data = [
        # Kardiyovasküler
        ("Kaptopril", ["Farmakoloji", "Kardiyoloji"], ["ace inhibitoru", "kuru oksuruk", "sulfhidril grubu", "tat bozuklugu dysgeusia"]),
        ("Lizinopril", ["Farmakoloji", "Kardiyoloji"], ["ace inhibitoru", "on ilac degildir", "aktif formda atilir"]),
        ("Perindopril", ["Farmakoloji", "Kardiyoloji"], ["ace inhibitoru", "uzun etkili", "doku afinitesi"]),
        ("Kandesartan", ["Farmakoloji", "Kardiyoloji"], ["arb", "at1 reseptor blokoru", "kalp yetmezligi"]),
        ("İrbesartan", ["Farmakoloji", "Kardiyoloji", "Nefroloji"], ["arb", "diyabetik nefropati mikroalbuminuri"]),
        ("Telmisartan", ["Farmakoloji", "Kardiyoloji"], ["arb", "ppar gama parsiyel agonisti insülin duyarliligi"]),
        ("Olmesartan", ["Farmakoloji", "Kardiyoloji", "Gastroenteroloji"], ["arb", "sprue benzeri enteropati kronik diyare"]),
        ("Felodipin", ["Farmakoloji", "Kardiyoloji"], ["dihidropiridin kkb", "damar secici", "hipertansiyon"]),
        ("Nikardipin", ["Farmakoloji", "Kardiyoloji", "Acil Tıp"], ["dihidropiridin kkb iv", "hipertansif acil beyin kanamasi"]),
        ("Klevidipin", ["Farmakoloji", "Kardiyoloji", "Anesteziyoloji ve Reanimasyon"], ["ultra kisa etkili kkb", "plazma esterazlari ile yikim", "acil kan basinci kontrolu"]),
        ("Lerkanidipin", ["Farmakoloji", "Kardiyoloji"], ["dihidropiridin kkb", "lipofilik", "daha az ayak bilegi odemi"]),
        ("Nebivolol", ["Farmakoloji", "Kardiyoloji"], ["beta 1 secici bloker", "nitrik oksit no salinimi endotelyal vazodilatasyon"]),
        ("Bisoprolol", ["Farmakoloji", "Kardiyoloji"], ["beta 1 secici bloker", "kalp yetmezliginde mortalite azalmasi"]),
        ("Esmolol", ["Farmakoloji", "Kardiyoloji", "Acil Tıp"], ["ultra kisa etkili beta 1 bloker", "eritrosit esterazlari ile yikim", "aort diseksiyonu perioperatif tasikardi"]),
        ("Sotalol", ["Farmakoloji", "Kardiyoloji"], ["non selektif beta bloker", "sinif 3 antiaritmik potasyum kanal blokoru", "torsades de pointes qt uzamasi"]),
        ("Labetalol", ["Farmakoloji", "Kardiyoloji", "Kadın Hastalıkları ve Doğum"], ["alfa 1 ve beta bloker", "gebelik hipertansiyonu preeklampsi"]),
        ("Bumetanid", ["Farmakoloji", "Kardiyoloji"], ["kivrim loop diuretigi", "furosemidden 40 kat guclu"]),
        ("Etakrinik Asit", ["Farmakoloji", "Kardiyoloji"], ["sulfonamid yapisinda olmayan loop diuretigi", "sulfa alerjisinde guvenli", "en cok ototoksisite yapan diuretik"]),
        ("İndapamid", ["Farmakoloji", "Kardiyoloji"], ["tiyazid benzeri diuretik", "kalsiyum kanal blokaji vazodilatasyon"]),
        ("Metolazon", ["Farmakoloji", "Kardiyoloji", "Nefroloji"], ["tiyazid benzeri diuretik", "gfr dusukken bile etkili diuretik direnci"]),
        ("Amilorid", ["Farmakoloji", "Nefroloji"], ["enac epitelyal sodyum kanal blokoru", "liddle sendromu tedavisi lityum poliurisi"]),
        ("Triamteren", ["Farmakoloji", "Nefroloji"], ["enac sodyum kanal blokoru", "bobrek tasi olusumu"]),
        ("Asetazolamid", ["Farmakoloji", "Göz Hastalıkları", "Nöroloji"], ["karbonik anhidraz inhibitoru", "proksimal tubul", "glokom goz ici basinci", "dag hastaligi yukseklik irtifa", "idrar alkalilestirme"]),
        ("Mannitol", ["Farmakoloji", "Nöroloji", "Beyin ve Sinir Cerrahisi"], ["ozmotik diuretik", "kan beyin bariyeri intrakraniyal basinc dusurucu", "beyin odemi"]),
        ("Dobutamin", ["Farmakoloji", "Kardiyoloji", "Acil Tıp"], ["beta 1 adrenerjik agonist", "pozitif inotrop", "kardiyojenik sok kalp yetmezligi"]),
        ("Milrinon", ["Farmakoloji", "Kardiyoloji"], ["fosfodiesteraz 3 pde3 inhibitoru", "inodilatator", "ileri evre kalp yetmezligi"]),
        ("Levosimendan", ["Farmakoloji", "Kardiyoloji"], ["kalsiyum duyarlaştirici troponin c", "inotrop vazodilatator"]),
        ("Prazosin", ["Farmakoloji", "Kardiyoloji", "Psikiyatri"], ["alfa 1 adrenerjik reseptor blokoru", "ptsd kabuslari travma sonrasi stres"]),
        ("Doksazosin", ["Farmakoloji", "Kardiyoloji", "Üroloji"], ["alfa 1 bloker", "bph iyi huylu prostat hiperplazisi ve hipertansiyon"]),
        ("Tamsulosin", ["Farmakoloji", "Üroloji"], ["alfa 1a secici reseptor blokoru prostat spesifik", "bph alt uriner sistem semptomlari luts", "ortostatik hipotansiyon az intraoperatif gevsek iris sendromu"]),
        ("Alfuzosin & Silodosin", ["Farmakoloji", "Üroloji"], ["alfa 1a bloker", "retrograd ejakulasyon silodosin"]),
        ("Minoksidil", ["Farmakoloji", "Kardiyoloji", "Dermatoloji"], ["k atp kanal acici potasyum kanali damar duz kasi", "direkt arteriyol vazodilatator", "hipertrikoz sac dokulmesi androgenetik alopesi"]),
        ("Diazoksit", ["Farmakoloji", "Endokrinoloji"], ["k atp kanal acici pankreas beta hucreleri", "insulin salinimini bloke eder", "insulinoma refrakter hipoglisemi"]),
        ("Bosentan & Ambrisentan", ["Farmakoloji", "Göğüs Hastalıkları", "Kardiyoloji"], ["endotelin 1 reseptor antagonisti eta etb", "pulmoner arteriyel hipertansiyon pah", "hepatotoksisite ve teratojen"]),
        ("Sildenafil & Tadalafil", ["Farmakoloji", "Üroloji", "Kardiyoloji"], ["fosfodiesteraz 5 pde5 inhibitoru cgmp artisi", "erektil disfonksiyon", "pulmoner hipertansiyon revatio", "mavi gorme siyanopsi", "nitratlarla kesin kontrendike olumcul hipotansiyon"]),
        ("Riociguat", ["Farmakoloji", "Göğüs Hastalıkları"], ["cozunur guanilat siklaz sgc uyarici", "kronik tromboembolik pulmoner hipertansiyon cteph"]),
        ("Epoprostenol & İloprost", ["Farmakoloji", "Göğüs Hastalıkları"], ["prostasiklin pgı2 analoglari", "pulmoner vazodilatator trombosit agregasyon inhibitoru"]),
        ("Ranolazin", ["Farmakoloji", "Kardiyoloji"], ["gec sodyum akimi ina inhibitoru miyosit kalsiyum yukunu azaltir", "refrakter kronik stabil angina"]),
        ("Trimetazidin", ["Farmakoloji", "Kardiyoloji"], ["yag asidi beta oksidasyon inhibitoru glukoz oksidasyonunu artirir", "antianginal metabolik ajan"]),
        ("Kinidin", ["Farmakoloji", "Kardiyoloji"], ["sinif 1a antiaritmik na ve k kanal blokaji", "cinhonizm bas agrisi kulak cinlamasi gorme bozuklugu", "trombositopeni digoksin duzeyini iki katina cikarir"]),
        ("Prokainamid", ["Farmakoloji", "Kardiyoloji"], ["sinif 1a antiaritmik", "wpw de atriyal fibrilasyon tedavisi", "ilaca bagli lupus sendromu anti histon antikorlari yavas asetilleyiciler"]),
        ("Dizopiramid", ["Farmakoloji", "Kardiyoloji"], ["sinif 1a antiaritmik", "guclu antikolinerjik yan etkiler idrar retansiyonu glokom"]),
        ("Lidokain", ["Farmakoloji", "Kardiyoloji", "Acil Tıp"], ["sinif 1b antiaritmik na kanali inaktivasyonunu hizlandirir", "iskemik ventrikuler aritmiler mi sonrasi vt", "atriyal dokuda etkisizdir"]),
        ("Meksiletin", ["Farmakoloji", "Kardiyoloji"], ["sinif 1b antiaritmik oral form", "uzun qt sendromu tip 3"]),
        ("Flekainid & Propafenon", ["Farmakoloji", "Kardiyoloji"], ["sinif 1c antiaritmik belirgin na kanal blokaji qrs genislemesi", "yapısal kalp hastaligi olmayanlarda paroksismal af ritim kontrolu pill in the pocket", "cast calismasi mi gecirenlerde proaritmik olumcul kontrendike"]),
        ("Dronedaron", ["Farmakoloji", "Kardiyoloji"], ["amiodaron turevi iyotsuz", "tiroid toksisitesi yoktur", "kalp yetmezliginde kontrendike"]),
        ("Adenozin", ["Farmakoloji", "Kardiyoloji", "Acil Tıp"], ["a1 purinerjik reseptor agonisti av dugum hiperpolarizasyonu potasyum cikisi", "supraventrikuler tasikardi svt sonlandirma ilk tercih", "yari omru 10 saniyeden kisa santral iv bolus", "teofilin kafein etkisini bloke eder dipiridamol guclendirir"]),
        ("Klostiramin & Kolestipol", ["Farmakoloji", "Gastroenteroloji", "Kardiyoloji"], ["safra asidi baglayan recineler", "barsakta safra asitlerini baglar ldl yi dusurur", "trigliserit duzeyini artirabilir", "yagda eriyen vitamin ade k emilim bozuklugu"]),
        ("Bempedoik Asit", ["Farmakoloji", "Kardiyoloji"], ["atp sitrat liyaz acly inhibitoru kolesterol sentezini karacigerde erken basamakta bloke eder", "statin intoleransi olan hastalarda ldl dusurucu kas agrisi yapmaz"]),
        ("İkosapent Etil", ["Farmakoloji", "Kardiyoloji"], ["yuksek saflikta epa omega 3 yag asidi", "trigliserit dusurucu kardiyovaskuler olaylari azaltir"]),

        # SSS, Nöroloji ve Psikiyatri
        ("Klonazepam", ["Farmakoloji", "Nöroloji", "Psikiyatri"], ["benzodiazepin", "uzun etkili antikonvulzan", "miyoklonik nobetler panik bozukluk"]),
        ("Alprazolam (Xanax)", ["Farmakoloji", "Psikiyatri"], ["kisa orta etkili benzodiazepin", "panik atak panik bozukluk", "hizli bagimlilik ve yoksunluk"]),
        ("Flunitrazepam", ["Farmakoloji", "Psikiyatri"], ["guclu hipnotik benzodiazepin", "amnezi yapici rohypnol"]),
        ("Flumazenil", ["Farmakoloji", "Acil Tıp", "Anesteziyoloji ve Reanimasyon"], ["benzodiazepin reseptor kompetitif antagonisti", "benzodiazepin zehirlenmesi antidotu", "kronik kullanicilarda ani yoksunluk ve nobet tetikleyebilir"]),
        ("Ramelteon", ["Farmakoloji", "Psikiyatri"], ["melatonin mt1 mt2 reseptor agonisti suprakiazmatik nukleus", "uykuya dalma bozuklugu insomni bagimlilik yapmaz"]),
        ("Suvoreksant", ["Farmakoloji", "Psikiyatri"], ["oreksin hypocretin reseptor antagonisti ox1r ox2r", "uyku bozuklugu insomni"]),
        ("Buspiron", ["Farmakoloji", "Psikiyatri"], ["5 ht1a parsiyel agonisti", "yaygin anksiyete bozuklugu", "sedasyon bagimlilik yapmaz etkisi 2 4 haftada baslar"]),
        ("Fosfenitoin", ["Farmakoloji", "Nöroloji", "Acil Tıp"], ["fenitoin suda eriyen on ilaci", "iv ve im uygulanabilir mor el sendromu yapmaz"]),
        ("Lakozamid", ["Farmakoloji", "Nöroloji"], ["yavas sodyum kanal inaktivasyonu guclendirici", "direncli fokal nobetler"]),
        ("Zonisamid", ["Farmakoloji", "Nöroloji"], ["na ve t tipi ca kanal blokaji karbonik anhidraz zayif", "sulfonamid turevi kilo kaybi bobrek tasi"]),
        ("Vigabatrin", ["Farmakoloji", "Nöroloji", "Pediatri"], ["gaba transaminaz gaba t geri donussuz inhibitoru", "infantil spazm west sendromu tuberosklerozda ilk tercih", "kalici gorme alani daralmasi konsantrik korluk"]),
        ("Tiagabin", ["Farmakoloji", "Nöroloji"], ["gat 1 gaba geri alim tasiyici inhibitoru", "sinapsta gaba konsantrasyonunu artirir"]),
        ("Rufinamid", ["Farmakoloji", "Nöroloji", "Pediatri"], ["sodyum kanal inaktivasyonu uzamasi", "lennox gastaut sendromu nobetleri"]),
        ("Felbamat", ["Farmakoloji", "Nöroloji"], ["nmda glisin alani blokaji", "aplastik anemi ve fulminan karaciger yetmezligi kara kutu uyari"]),
        ("Perampanel", ["Farmakoloji", "Nöroloji"], ["non kompetitif ampa glutamat reseptor antagonisti", "nobet kontrolu agir agresyon psikiyatri"]),
        ("Entekapon & Tolkapon", ["Farmakoloji", "Nöroloji"], ["comt katekol o metiltransferaz inhibitorleri", "levodopanın 3 o metildopaya donusumunu engeller", "tolkapon kan beyin bariyerini gecer hepatotoksisite tolkapon"]),
        ("Apomorfin", ["Farmakoloji", "Nöroloji"], ["guclu d1 d2 dopamin agonisti subkutan enjeksiyon", "parkinson hastaliginda agir akut donma akinezi off kurtarma", "agir emetik etki trimetobenzamid premedikasyonu"]),
        ("Amantadin", ["Farmakoloji", "Nöroloji"], ["dopamin salinimini artirir nmda antagonisti", "parkinson levodopaya bagli diskineziler", "livedo retikularis bacaklarda dantelsi mor lezyonlar periferik odem"]),
        ("Donepezil, Rivastigmin & Galantamin", ["Farmakoloji", "Nöroloji"], ["santral asetilkolinesteraz inhibitorleri achei", "alzheimer demans hafif orta evre semptomatik", "parasempatik yan etkiler bradikardi senkop bulanti diyare kilo kaybi"]),
        ("Memantin", ["Farmakoloji", "Nöroloji"], ["orta afiniteli voltaj bagimli nmda reseptor antagonisti", "glutamat eksitotoksisitesini onler", "orta ileri evre alzheimer demans"]),
        ("Lekanemab & Donanemab", ["Farmakoloji", "Nöroloji"], ["amiloid beta protofibril monoklonal antikorlari", "erken evre alzheimer plak temizleme", "aria amiloid iliskili goruntuleme anormallikleri beyin odemi kanama"]),
        ("Baklofen", ["Farmakoloji", "Nöroloji", "Fiziksel Tıp ve Rehabilitasyon"], ["gaba b reseptor agonisti", "omurilik duzeyinde monosinaptik ve polisinaptik refleksleri inhibe eder", "multipl skleroz ve spinal travma spastisitesi"]),
        ("Tizanidin", ["Farmakoloji", "Nöroloji"], ["santral alfa 2 adrenerjik agonist", "omurilik motor noron inhibisyonu kas gevsetici"]),
        ("Dantrolen Sodyum", ["Farmakoloji", "Anesteziyoloji ve Reanimasyon", "Acil Tıp"], ["riyanodin reseptoru ryr1 blokoru", "sarkoplazmik retikulumdan kalsiyum salinimini bloke eder", "malign hipertermi anestezik uyarilmis", "noroleptik malign sendrom nms antidotu"]),
        ("Botulinum Toksini (Botoks)", ["Farmakoloji", "Nöroloji", "Dermatoloji"], ["snare proteinlerini parcalar asetilkolin salinimini onler", "fokal distoni blefarospazm spastisite asiri terleme migren"])
    ]
    for name, discs, terms in pharm_data:
        items.append((name, discs, terms))

    # 2. KLİNİK VE PATOLOJİK SENDROMLAR, İŞARETLER VE ENFEKSİYONLAR
    clinical_data = [
        # Endokrin & Metabolizma
        ("Cushing Sendromu & Tanı Algoritması", ["Endokrinoloji", "Dahiliye"], ["cushing sendromu", "hiperkortizolizm", "aydede yuzu", "bufalo horgucu ense yag yastigi", "mor genital strialar", "hipertansiyon osteoporoz kas atrofisi", "24 saatlik idrar serbest kortizolu", "gece tukuruk kortizolu", "1 mg gece deksametazon supresyon testi", "acth bagimli hipofiz cushing hastaligi veya ektopik kucuk hucreli akciger ca"]),
        ("Addison Hastalığı & Akut Adrenal Kriz", ["Endokrinoloji", "Dahiliye", "Acil Tıp"], ["addison hastaligi", "primer adrenal yetmezlik", "korteks harabiyeti 21 hidroksilaz otoantikor", "kortizol ve aldosteron eksikligi", "acth yuksekligi pomc proopiomelanokortin hiperpigmentasyon agiz mukozasi katlantilar", "hiponatremi hiperkalemi hipotansiyon hipoglisemi", "su ve tuz kaybi dehidratasyon", "adrenal kriz acil hidrokortizon ve serum fizyolojik"]),
        ("Feokromositoma & Metanefrinler", ["Endokrinoloji", "Genel Cerrahi", "Tıbbi Patoloji"], ["feokromositoma", "adrenal medulla kromaffin hucreli tumor zellballen paterni", "paroksismal hipertansiyon 5p bas agrisi terleme carpinti solukluk palpitasyon", "plazma serbest metanefrinler ve 24 saatlik idrar vma metanefrin", "yuzde 10 kurali bilateral ekstraadrenal malign cocuk ailesel", "men 2a 2b vhl nf1 iliskisi", "cerrahi oncesi mutlak alfa bloker fenoksibenzamin sonra beta bloker"]),
        ("Primer Hiperaldosteronizm (Conn Sendromu)", ["Endokrinoloji", "Nefroloji", "Kardiyoloji"], ["conn sendromu", "primer hiperaldosteronizm", "adrenal aldosteron ureten adenom zona glomerulosa", "hipertansiyon hipokalemi metabolik alkaloz", "plazma renin aktivitesi baskilanmistir", "aldosteron renin orani 30 ustu", "spironolakton eplerenon tedavisi"]),
        ("Akromegali & Oral Glukoz Tolerans Testi", ["Endokrinoloji", "Beyin ve Sinir Cerrahisi"], ["akromegali", "buyume hormonu gh salgilayan hipofiz somatotrop adenomu", "igf 1 somatomedin c duzeyinde artis en duyarli tarama", "ogtt oral glukoz tolerans testi ile gh baskilanamamasi tani testi", "el ayak ayakkabi numarasinda buyume yuz hatlarinda kabalasma prognatizm dil buyumesi makroglossi", "karpal tunel sendromu bitemporal hemianopsi optik kiyazma basisi kolon polipleri"]),
        ("Prolaktinoma & Dopamin Agonistleri", ["Endokrinoloji", "Kadın Hastalıkları ve Doğum", "Beyin ve Sinir Cerrahisi"], ["prolaktinoma", "en sik islevsel hipofiz adenomu mikroadenom makroadenom", "kadinlarda galaktore meme basi akintisi amenore infertilite", "erkeklerde libido kaybi erektil disfonksiyon jinekomasti", "kabergolin bromokriptin ilk tercih medikal tedavi cerrahi nadir"]),
        ("Diabetes İnsipidus (Santral vs Nefrojenik)", ["Endokrinoloji", "Nefroloji"], ["diabetes insipidus", "di", "agir poliuri polidipsi seyreltik idrar idrar dansitesi 1005 alti", "santral di hipotalamus hipofiz adh vasopresin eksikligi travma cerrahi desmopresine yanit verir", "nefrojenik di v2 reseptor direnci lityum hipokalemi hiperkalsemi desmopresine yanitsiz"]),
        ("Uygunsuz ADH Sendromu (SIADH)", ["Endokrinoloji", "Dahiliye", "Onkoloji"], ["siadh", "uygunsuz antidiuretik hormon salinimi sendromu", "ovolemik hiponatremi idrar sodyumu 40 ustu", "idrar osmolaritesi plazma osmolaritesinden yuksek", "kucuk hucreli akciger karsinomu paraneoplastik ssri karbamazepin kafa travmasi", "sivi kisitlamasi tolvaptan konivaptan hipertonik salin yavas duzeltme santral pontin miyelinolizis riski"]),
        ("Diyabetik Ketoasidoz (DKA)", ["Endokrinoloji", "Dahiliye", "Acil Tıp"], ["diyabetik ketoasidoz", "dka", "tip 1 diyabet mutlak insulin eksikligi", "triad hiperglisemi ketonemi idrarda keton yuksek anyon acikli metabolik asidoz", "kussmaul solunumu aseton kokulu nefes karin agrisi kusma", "iv hidrasyon potasyum replasmani reguler kristalize insulin"]),
        ("Hiperozmolar Hiperglisemik Durum (HHS)", ["Endokrinoloji", "Dahiliye", "Acil Tıp"], ["hhs", "hiperozmolar hiperglisemik nonketotik koma", "tip 2 diyabet yasli enfeksiyon tetikleyici", "asiri kan sekeri 600 ustu plazma ozmolaritesi 320 ustu agir dehidratasyon", "asidoz ve ketonemi yoktur veya hafiftir koma letarji", "masif sivi replasmani en kritik basamak"]),

        # Hematoloji & Onkoloji
        ("Demir Eksikliği Anemisi & Plummer-Vinson", ["Hematoloji", "Dahiliye", "Gastroenteroloji"], ["demir eksikligi anemisi", "mikrositik hipokrom anemi", "serum demiri dusuk tdbk yuksek ferritin dusuk en guvenilir", "anizositoz rdw artisi", "pika toprak buz yeme koilonisi kasik tirnak atrofik glossit", "plummer vinson sendromu demir eksikligi ozofageal web disfaji skuamoz ca"]),
        ("Megaloblastik Anemi & B12 vs Folat", ["Hematoloji", "Dahiliye"], ["megaloblastik anemi", "makrositik anemi mcv 100 ustu", "kemik iliginde megaloblastlar kanda hipersegmente notrofiller 5 lob ustu", "b12 eksikligi kobalamin pernisiyoz anemi intrensek faktor antikoru metilmalonik asit ve homosistein yuksek", "subakut kombine dejenerasyon arka ve yan kordon demiyelinizasyonu parestezi ataksi", "folat eksikligi yalnizca homosistein yuksek norolojik bulgu yoktur"]),
        ("Orak Hücreli Anemi (HbS) & Krizler", ["Hematoloji", "Pediatri", "Tıbbi Genetik"], ["orak hucreli anemi", "hbs", "beta globin 6 pozisyon glutamik asit yerine valin", "deoksijene durumda polimerizasyon oraklasma", "vazookluzif agri krizleri daktilit el ayak sendromu cocukta", "akut gogus sendromu dalak otosplenektomisi howell jolly cisimcikleri", "kapsullu bakteri enfeksiyonlari pnomokok salmonella osteomiyelit", "hidroksiüre fetal hemoglobin hbf artisi"]),
        ("Talasemi Majör (Cooley Anemisi) & Minör", ["Hematoloji", "Pediatri", "Tıbbi Genetik"], ["talasemi", "akdeniz anemisi", "talasemi minor tasiyici mikrositoz eritrosit sayisi rbc yuksek mentzer indeksi 13 alti", "talasemi major cooley anemisi beta zincir yoklugu hba yok agir mikrositik anemi", "hedef hucreler target cells", "kemik iligi hiperaktivitesi kule kafa firca sac kafatasi kemik deformiteleri", "kronik kan transfuzyonu demir yuklenmesi hemokromatozis demir selasyonu deferoksamin"]),
        ("İmmün Trombositopenik Purpura (ITP)", ["Hematoloji", "Dahiliye", "Pediatri"], ["itp", "immun trombositopenik purpura", "anti gpiib iiia antikorlari trombosit harabiyeti dalakta fagositoz", "izole trombositopeni baska seriler normal", "kemik iliginde megakaryosit sayisi artmis", "mukokutanoz kanamalar petesi purpura ekimoz burun kanamasi", "steroid ivig splenektomi"]),
        ("Trombotik Trombositopenik Purpura (TTP) Pentadı", ["Hematoloji", "Dahiliye", "Nefroloji"], ["ttp", "trombotik trombositopenik purpura", "adamts13 metalloproteinaz enzim eksikligi otoantikor", "ultra buyuk vwf multimerleri mikrovaskuler trombosit tıkaclari", "klasik pentad 1 trombositopeni 2 maha mikroanjiyopatik hemolitik anemi sistositler 3 norolojik semptomlar konfuzyon bas agrisi 4 akut bobrek yetmezligi 5 ates", "acil plazmaferez plazma degisimi plazma transfuzyonu kesinlikle trombosit verilmez kontraendike"]),
        ("Yaygın Damar İçi Pıhtılaşma (DİK / DIC)", ["Hematoloji", "Acil Tıp", "Yoğun Bakım"], ["dik", "yaygin damar ici pihtilasma", "tuketim koagulopatisi yaygin mikrovaskuler tromboz ve masif kanama ayni anda", "sepsis agir travma obstetrik komplikasyonlar ablasyo amniyon embolisi losemi apl", "d dimer ve fdp fibrin yikim urunleri belirgin yuksek", "trombosit fibrinojen faktorler tukenir pt ve aptt uzar", "tedavi altta yatan nedeni cozmek tdp trombosit kriyopresipitat"]),
        ("Multipl Miyelom & CRAB Kriterleri", ["Hematoloji", "Tıbbi Onkoloji"], ["multipl miyelom", "plazma hucre diskrazisi klonal cd138 cd38 plazmosit", "spep m spike monoklonal igg iga paraprotein", "idrarda bence jones proteini hafif zincir", "crab kriterleri 1 kalsiyum yuksekligi hiperkalsemi 2 renal yetmezlik miyelom bobregi kalsiyum hafif zincir silendirleri 3 anemi normositer yorgunluk 4 bone kemik litik zimbayla delinmis punche out lezyonlar patolojik kirik", "eritrosit rulo formasyonu rouleaux"]),
        ("Kronik Miyeloid Lösemi (KML) & İmatinib", ["Hematoloji", "Tıbbi Onkoloji"], ["kml", "kronik miyeloid losemi", "t 9 22 philadelphia kromozomu bcr abl fuzon geni tirosin kinaz aktivasyonu", "masif lokositoz sola kayma promiyelosit miyelosit bazofili eozinofili splenomegali", "lokosit alkalen fosfataz lap skoru cok dusuktur lokomoid reaksiyondan ayrim", "imatinib gleevac tirozin kinaz inhibitoru hedefli tedavi"]),
        ("Akut Promiyelositik Lösemi (APL - AML M3)", ["Hematoloji", "Tıbbi Onkoloji"], ["apl", "akut promiyelositik losemi", "t 15 17 pml rara fuzon geni retinoik asit reseptor defekti", "cok sayida auer comagi faggot cells", "en sik dik yaygin damar ici pihtilasma tetikleyen losemi", "atra all trans retinoik asit ve arsenik trioksit hucre diferansiasyonu kur"]),

        # Nöroloji ve Beyin Cerrahisi
        ("İskemik İnme & Trombolitik Tedavi Penceresi", ["Nöroloji", "Acil Tıp"], ["iskemik inme", "svo", "ani fokal norolojik defisit hemiparezi hemipleji afazi", "kontrastsiz beyin bt kanamayi dislamak icin hemen", "iv alteplaz tpa ilk 4 5 saat icinde", "endovaskuler mekanik trombektomi buyuk damar tikanikligi lvo ilk 6 24 saat penumbra"]),
        ("Epidural Hematom & Lusid İnterval", ["Beyin ve Sinir Cerrahisi", "Acil Tıp"], ["epidural hematom", "arteria meningea media yirtilmasi", "temporal kemik pterion kirigi kafa travmasi", "lusid interval berrak aralik travma sonrasi kisa bayilma ayilma sonra ani koma", "bt de hiperdens bikonveks merceksi lens seklinde hematom sutur cizgilerini asmaz", "acil kraniyotomi drenaj"]),
        ("Subdural Hematom & Köprü Venler", ["Beyin ve Sinir Cerrahisi", "Nöroloji"], ["subdural hematom", "kopru venlerin bridging veins yirtilmasi venoz kanama", "yaslilarda alkoliklerde beyin atrofisi hafif travma sonrasi sinsi", "bt de kresent hilal seklinde hematom sutur cizgilerini asar dural sinuse kadar uzanir"]),
        ("Subaraknoid Kanama (SAK) & Anevrizma", ["Beyin ve Sinir Cerrahisi", "Nöroloji", "Acil Tıp"], ["subaraknoid kanama", "sak", "berry sakuler anevrizma rupture anterior komünikan arter acoa en sik", "hayatimin en siddetli bas agrisi gok gurultusu bas agrisi ani ense sertligi meningeal iritasyon", "bt de subaraknoid sisternalarda kanama eger bt normal ise lomber ponksiyon ksantokromi", "vazospazm komplikasyonu nimodipin kalsiyum kanal blokoru"]),
        ("Multipl Skleroz (MS) & Oligoklonal Bant", ["Nöroloji", "Tıbbi Patoloji"], ["multipl skleroz", "ms", "santral sinir sistemi otoimmun demiyelinizan plaklar mekanda ve zamanda yayilim", "optik norit agrisi goz hareketiyle monokuler gorme kaybi", "internukleer oftalmopleji mlf lezyonu", "lhermitte belirtisi boyun fleksiyonu ile elektrik carpmasi", "bos ta oligoklonal igg bantlari mri da periventrikuler dawson parmaklari plaklar"]),
        ("Myastenia Gravis & Tensilon Testi", ["Nöroloji", "Göğüs Cerrahisi"], ["myastenia gravis", "anti achr postsinaptik asetilkolin reseptoru otoantikoru", "kas yorgunlugu fatigabilite gunun ilerleyen saatlerinde artan pitozis diplopi cigneme zorlugu", "tensilon edrofonyum testi ile semptomlarin ani duzelmesi", "timoma yuzde 15 veya timik hiperplazi yuzde 65 toraks bt ve timektomi", "piridostigmin oral antikolinesteraz"]),
        ("Guillain-Barré Sendromu (AIDP)", ["Nöroloji", "Enfeksiyon Hastalıkları"], ["guillain barre", "aidp", "akut inflamatuar demiyelinizan polinöropati", "campylobacter jejuni veya viral gribal enfeksiyon sonrasi", "asendan yukselen simetrik flask felc ayaklardan baslayan bacaklara kollara solunuma yayilan", "derin tendon refleksleri dtr kaybi arefleksi", "bos incelemesinde albuminositolojik disosiasyon protein yuksek hucre sayisi normal", "ivig ve plazmaferez steroid etkisizdir"]),

        # Romatoloji
        ("Romatoid Artrit (RA) & Deformiteler", ["Romatoloji", "Fiziksel Tıp ve Rehabilitasyon"], ["romatoid artrit", "ra", "simetrik kucuk eklem poliartriti mcp pif el bilegi dif eklemler korunur", "sabah tutuklugu 1 saatten uzun", "sinovyal hipertrofi pannus kikirdak erozyonu", "kugu boynu deformitesi dugme iligi deformitesi ulnar deviasyon", "romatoid faktor rf ve anti ccp siklik sitruline peptid en ozgul", "metotreksat ilk tercih dmard"]),
        ("Sistemik Lupus Eritematozus (SLE)", ["Romatoloji", "Dahiliye", "Tıbbi İmmünoloji"], ["sle", "sistemik lupus eritematozus", "tip 3 asiri duyarlilik otoimmun", "malar ras kelebek dokuntu nazolabial kivrimlari korur", "fotosensitivite diskoid lezyonlar oral aftoz ulserler serozit plorit perikardit", "ana antinukleer antikor en duyarli tarama", "anti dsdna ve anti smith anti sm en ozgul", "kompleman c3 ve c4 duzeyinde dusus lupus nefriti aktivite gostergesi", "libman sacks endokarditi iki yuzlu steril vejetasyon"]),
        ("Ankilozan Spondilit & Bambu Kamışı", ["Romatoloji", "Fiziksel Tıp ve Rehabilitasyon"], ["ankilozan spondilit", "hla b27 pozitifligi seronegatif spondiloartropati rf negatif", "genc erkekte inflamatuar bel agrisi istirahatle artan egzersizle azalan gece uyandiran", "bilateral simetrik sakroiliit omurgada sindesmofitler bambu kamisi omurga", "entezit asil tendiniti akut anterior uveit gozde kizariklik agri", "aort yetersizligi apikal akciger fibrozisi", "schober testi omurga hareket kisitliligi"]),
        ("Gut Artriti & Monosodyum Ürat Kristalleri", ["Romatoloji", "Ortopedi ve Travmatoloji"], ["gut", "gut artriti", "hiperurisemi zemininde monosodyum urat kristal cokmesi", "akut monoartrit 1 metatarsofalangeal eklem podagra gece ani baslayan kizariklik sislik siddetli agri", "eklem sivisi mikroskopisinde igne seklinde negatif cift kirinim gosteren kristaller polarize isikta sari", "kronik tofus tofusler kulak kepcesi dirsek olekranon", "akut atakta nsaid kolşisin steroid profilakside allopurinol febuksostat urikozurik"]),

        # Pediatri
        ("Yenidoğan Respiratuar Distres Sendromu (RDS)", ["Pediatri", "Neonatoloji"], ["respiratuar distres sendromu", "rds", "prematurite surfaktan eksikligi tip 2 alveolar hucreler dipalmitoilfosfatidilkolin", "diffuz mikroatelektaziler camsi hyalen membranlar", "telede buzlu cam ground glass retikulogranuler gorunum hava bronkogramlari", "ekspiratuar inleme grunting takipne burun kanadi solunumu subkostal cekilmeler", "antenatal maternal betametazon profilaksisi ekzojen endotrakeal surfaktan"]),
        ("Nekrotizan Enterokolit (NEK)", ["Pediatri", "Neonatoloji", "Çocuk Cerrahisi"], ["nekrotizan enterokolit", "nek", "prematüre bebekte formula mama ile beslenme sonrasi", "karin distansiyonu batinda hassasiyet safrali kusma kanli gaita", "direkt batin grafisinde pnomatozis intestinalis barsak duvarinda hava cift kontur", "portal vende gaz serbest hava pnomoperitoneum perforasyon cerrahi acil"]),
        ("Hipertrofik Pilor Stenozu & Zeytin Belirtisi", ["Pediatri", "Çocuk Cerrahisi"], ["hipertrofik pilor stenozu", "ilk cocuk erkek 3 6 haftalik", "fiskirir tarzda safrasiz kusma her beslenmeden sonra acikma", "epigastriumda zeytin benzeri palpabl kitle olive sign", "hipokloremik hipokalemik metabolik alkaloz dehidratasyon", "ultrasonda pilor kas kalinligi 4 mm pilor kanali 14 mm ustu", "piloromiyotomi fredet ramstedt"]),
        ("İntussusepsiyon (Bağırsak İnvajinasyonu)", ["Pediatri", "Çocuk Cerrahisi", "Radyoloji"], ["intussusepsiyon", "invajinasyon", "bir barsak segmentinin digerinin icine teleskopik girmesi ileokolik en sik", "ani baslayan kolik karin agrisi nobetleri aglama krizleri bacaklari karna cekme", "cilek jolesi kivaminda kanli mukuslu gayta currant jelly stool", "sag ust kadranda sosis benzeri kitle sol alt bosluk dans dance belirtisi", "ultrasonda hedef tahtasi target sign boga gozu kokart belirtisi", "hava veya baryumlu lavman redüksiyon"]),
        ("Krup (Akut Laringotrakeobronşit)", ["Pediatri", "KBB", "Enfeksiyon Hastalıkları"], ["krup", "akut laringotrakeobronssit", "parainfluenza virus tip 1 en sik", "havlar tarzda oksuruk kopek havlamasi inspiratuar stridor ses kisikligi", "boyun grafisinde kule belirtisi steeple sign subglottik daralma", "buhar soguk hava nebülize budesonid veya deksametazon agır vakada nebulize rasemik epinefrin"]),
        ("Akut Epiglottit & Başparmak Belirtisi", ["Pediatri", "KBB", "Acil Tıp"], ["akut epiglottit", "haemophilus influenzae tip b hib asisiz cocuk", "ani yuksek ates toksik gorunum siddetli bogaz agrisi", "agzindan salya akmasi yutamama drooling", "tripod pozisyonu one egilme agiz acik boyun ekstansiyonda", "lateral boyun grafisinde basparmak belirtisi thumbprint sign odemli kiraz kirmizisi epiglottis", "asla abeslangla bogaza bakilmaz ani laringospazm hava yolu obstrüksiyonu acil entubasyon ameliyathane seftriakson"]),

        # Kadın Hastalıkları ve Doğum
        ("Preeklampsi & Eklampsi Kriterleri", ["Kadın Hastalıkları ve Doğum", "Perinatoloji"], ["preeklampsi", "gebeligin 20 haftasindan sonra yeni ortaya cikan hipertansiyon sistolik 140 diyastolik 90", "proteinuri 24 saatte 300 mg ustu veya trombositopeni bobrek kc yetmezligi gorme bozuklugu", "agir preeklampsi tansiyon 160 110 trombosit 100 bin alti ast alt iki kat pulmonary odem", "eklampsi preeklampsi zemininde baska nedene bagli olmayan jeneralize tonik klonik nobet", "nobet profilaksisi ve tedavisi magnezyum sulfat mgso4 kesin tedavi dogum"]),
        ("HELLP Sendromu", ["Kadın Hastalıkları ve Doğum", "Perinatoloji"], ["hellp sendromu", "h hemoliz periferik yaymada sistositler ldh 600 ustu indirekt bilirubin", "el elevated liver enzymes ast alt 70 ustu karaciger enzimlerinde artis", "lp low platelets trombositopeni trombosit 100 bin alti", "sag ust kadran epigastrik agri kapsul gerilmesine bagli subkapsuler hematom ve karaciger rupture riski", "acil dogum"]),
        ("Ektopik Gebelik & Rüptür", ["Kadın Hastalıkları ve Doğum", "Acil Tıp"], ["ektopik gebelik", "dis gebelik", "en sik yerlesim tuba uterina ampulla", "klasik triad amenore adet gecikmesi vajinal kanama akut pelvik kasik agrisi", "transvajinal ultrasonda kavite icinde gebelik kesesi izlenmezken beta hcg nin diskriminatuar zon 1500 2000 uzerinde olmasi", "adnekste ektopik odak tubal halka belirtisi batinda serbest sivi cul de sac ta kanama", "hemodinami stabil kitle kucuk kalp atimi yoksa metotreksat rüptüre ise acil laparoskopi"]),
        ("Plasenta Previa vs Ablasyo Plasenta", ["Kadın Hastalıkları ve Doğum"], [
            "plasenta previa", "plasentanin servikal ic osu kapatmasi veya yakini", "agrisiz parlak kirmizi vajinal kanama agrisizdir", "uterus yumusak ve gevsektir vajinal muayene kesinlikle kontrendikedir sezaryen dogum",
            "ablasyo plasenta", "plasentanin bebek dogmadan erken dekolmani ayrilmasi", "agrili koyu kirmizi kanama tahta gibi sert hassas uterus couvelaire uterus fetal distres dik riski"
        ])
    ]
    for name, discs, terms in clinical_data:
        items.append((name, discs, terms))

    return items
