# -*- coding: utf-8 -*-
"""
Medical Data Builder Module
Generates comprehensive clinical, pharmacological, microbiological,
pathological, and basic science concept entries.
"""

def get_pharmacology_concepts():
    items = []
    
    # Antibiyotikler
    abx = [
        ("Penisilin G & V", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["penisilin g", "penisilin v", "kristalize penisilin", "depo penisilin", "benzatin penisilin", "treponema sifiliz", "streptokok farenjiti", "beta laktam", "pbps transpeptidaz"]),
        ("Ampisilin & Amoksisilin", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["ampisilin", "amoksisilin", "aminopenisilin", "listeria monocytogenes", "enterokok", "amoksisilin klavulanat", "ogmentin", "ampisilin sulbaktam"]),
        ("Piperasilin-Tazobaktam (Tazosin)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["piperasilin", "tazobaktam", "tazosin", "antipsödomonal penisilin", "pseudomonas aeruginosa", "hastane kokenli pnomoni", "febril notropeni"]),
        ("Oksasilin, Nafsilin & Metisilin", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["oksasilin", "nafsilin", "metisilin", "dikloksasilin", "anti stafilokoksik penisilin", "penisilinaz direncli", "mssa", "mrsa meca geni"]),
        ("Sefazolin & Sefaleksin (1. Kuşak Sefalosporin)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["sefazolin", "sefaleksin", "1 kusak sefalosporin", "cerrahi profilaksi", "gram pozitif koklar", "selulit"]),
        ("Sefuroksim & Sefoksitin (2. Kuşak Sefalosporin)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["sefuroksim", "sefoksitin", "sefaklor", "2 kusak sefalosporin", "bacteroides fragilis", "anaerop etkinlik"]),
        ("Seftriakson & Sefotaksim (3. Kuşak Sefalosporin)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["seftriakson", "sefotaksim", "3 kusak sefalosporin", "menenjit tedavisi", "gonore bel soguklugu", "biliyer camur", "kan beyin bariyeri"]),
        ("Seftazidim (Antipsödomonal 3. Kuşak)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["seftazidim", "antipsodomonal sefalosporin", "pseudomonas", "avibaktam", "seftazidim avibaktam", "kpc karbapenemaz"]),
        ("Sefepim (4. Kuşak Sefalosporin)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["sefepim", "4 kusak sefalosporin", "ampc beta laktamaz", "pseudomonas", "febril notropeni"]),
        ("Seftarolin & Seftobiprol (5. Kuşak Anti-MRSA Sefalosporin)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["seftarolin", "seftobiprol", "5 kusak sefalosporin", "mrsa etkin sefalosporin", "pbp2a afinitesi"]),
        ("İmipenem, Meropenem & Ertapenem (Karbapenemler)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["imipenem", "meropenem", "ertapenem", "karbapenem", "esbl pozitif basiller", "silastatin dipeptidaz", "nobet riski imipenem"]),
        ("Aztreonam (Monobaktam)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["aztreonam", "monobaktam", "sadece gram negatif basil", "penisilin alerjisi guvenli", "pseudomonas"]),
        ("Vankomisin & Teikoplanin (Glikopeptidler)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["vankomisin", "teikoplanin", "glikopeptid", "d ala d ala baglanma", "mrsa ilk tercih", "red man kirmizi adam sendromu", "nefrotoksisite ototoksisite", "clostridioides difficile oral"]),
        ("Daptomisin (Kalsiyum Bağımlı Lipopeptid)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["daptomisin", "lipopeptid", "hucre zari depolarizasyonu", "vre vancomycin resistant enterococcus", "mrsa bakteriyemi", "survaktan inaktivasyonu akcigerde etkisiz", "kreatin kinaz miyopati"]),
        ("Gentamisin, Amikasin & Tobramisin (Aminoglikozidler)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["gentamisin", "amikasin", "tobramisin", "streptomisin", "aminoglikozid", "30s ribozom", "oksijene bagimli giris", "nefrotoksisite akut tubuler nekroz", "ototoksisite vestibulotoksisite", "noromuskuler blokaj"]),
        ("Azitromisin, Klaritromisin & Eritromisin (Makrolidler)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["azitromisin", "klaritromisin", "eritromisin", "makrolid", "50s ribozom", "atipik pnomoni mycoplasma chlamydia legionella", "motilin reseptor agonisti motilite", "qt uzamasi torsades de pointes", "cyp3a4 inhibisyonu"]),
        ("Klindamisin (Linkozamid)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["klindamisin", "linkozamid", "50s ribozom translokasyon", "diyafram ustu anaeroplar", "aspirasyon pnomonisi", "c difficile psodomembranoz kolit riski"]),
        ("Doksisiklin, Minosiklin & Tigesiklin (Tetrasiklinler)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["doksisiklin", "minosiklin", "tigesiklin", "tetrasiklin", "30s ribozom aminoasil trna", "kemik ve diste birikim sari dis", "cocuklarda ve gebelerde kontrendike", "bruselloz doksisiklin rifampisin", "riketsiya borelya lyme"]),
        ("Siprofloksasin, Levofloksasin & Moksifloksasin (Florokinolonlar)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["siprofloksasin", "levofloksasin", "moksifloksasin", "florokinolon", "dna giraz topoizomeraz 2 4", "tendon rüptürü asil tendiniti", "kıkırdak hasari artikuler toksisite", "qt uzamasi", "solunum kinolonu levofloksasin moksifloksasin"]),
        ("Linezolid & Tedizolid (Oksazolidinonlar)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["linezolid", "tedizolid", "oksazolidinon", "50s baslama kompleksi 70s", "vre tedavisi mrsa", "trombositopeni miyelosupresyon", "mao inhibisyonu serotonin sendromu", "optik ve periferik noropati"]),
        ("Trimetoprim-Sülfametoksazol (Kotrimoksazol / TMP-SMX)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["kotrimoksazol", "tmp smx", "bactrim", "dihidrofolat reduktaz dihidropteroat sentaz", "ardisik folat inhibisyonu", "pneumocystis jirovecii pjp pcp profilaksi", "nokardiya", "stenotrophomonas", "kernikterus hiperkalemi"]),
        ("Metronidazol & Tinidazol (Nitroimidazoller)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["metronidazol", "tinidazol", "flagyl", "serbest radikal dna hasari", "diyafram alti anaeroplar", "bacteroides fragilis", "clostridioides difficile", "giardia entamoeba trichomonas", "disulfiram benzeri reaksiyon alkolle"]),
        ("Kolistin & Polimiksin B (Polimiksinler)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["kolistin", "polimiksin b", "polimiksin e", "deterjan benzeri zar yikimi", "panrezistan gram negatif pan drug resistant pdr", "nefrotoksisite agir", "norotoksisite"]),
        ("Fosfomisin Trometamol", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları", "Üroloji"], ["fosfomisin", "monurol", "mura transferaz pyruvyl transferaz", "hucre duvari erken basamak", "komplike olmayan akut sistit tek doz"]),
        ("Nitrofurantoin", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları", "Üroloji"], ["nitrofurantoin", "piyelofer", "sistit tedavisi profilaksisi", "gfr 30 alti kontrendike", "akut ve kronik pulmoner fibrozis"]),
        ("İzoniyazid (INH)", ["Tıbbi Farmakoloji", "Göğüs Hastalıkları", "Enfeksiyon Hastalıkları"], ["izoniyazid", "inh", "mikolik asit sentez inhibisyonu inha", "tüberküloz ilaci", "periferik noropati piridoksin b6 eksikligi", "ilaca bagli hepatit hepatotoksisite", "yavas asetilleyici lupoid sendromu"]),
        ("Rifampisin & Rifabutin", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["rifampisin", "rifabutin", "dna bagimli rna polimeraz", "tuberkuloz cizgisi", "turuncu kirmizi vucut sivilari ter gozyasi", "guclu cyp450 induksiyonu etkilesim"]),
        ("Pirazinamid", ["Tıbbi Farmakoloji", "Göğüs Hastalıkları"], ["pirazinamid", "asidik ortamda aktif", "kazeoz granulom ici aktivite", "hiperurisemi gut alevlenmesi", "hepatotoksisite"]),
        ("Etambutol", ["Tıbbi Farmakoloji", "Göğüs Hastalıkları", "Göz Hastalıkları"], ["etambutol", "arabinozil transferaz embb", "retrobulber optik norit", "kirmizi yesil renk korlugu", "gorme keskinliginde azalma"])
    ]
    for name, discs, terms in abx:
        items.append((name, discs, terms))
        
    # Antifungaller
    antifungals = [
        ("Amfoterisin B (Lipozomal & Deoksikolat)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["amfoterisin b", "fungizone", "ergosterol por olusumu", "polien", "sistemik agir mikozlar", "infuzyon reaksiyonu titresim ates", "nefrotoksisite distal rta hipokalemi hipomagnezemi"]),
        ("Flukonazol", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["flukonazol", "diflucan", "14 alfa demetilaz inhibisyonu ergosterol", "kandida kriptokok menenjit profilaksi", "kan beyin bariyerini gecer", "c krusei ve c glabrata direncli"]),
        ("Vorikonazol", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["vorikonazol", "vfend", "invaziv aspergilloz ilk tercih", "gorsel fotopsi gorme bozukluklari parlama", "norotoksisite periostit floroza bagli"]),
        ("İtrakonazol", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["itrakonazol", "sporanox", "dimorfik mantarlar histoplazma blastomiçes sporotrikoz", "onikomikoz", "negatif inotrop kalp yetmezliginde kontrendike"]),
        ("Pozakonazol & İsavukonazol", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["pozakonazol", "isavukonazol", "mukormikozis mucor rhizopus", "genis spektrumlu triazol", "febril notropenik profilaksi"]),
        ("Kaspofungin, Mikafungin & Anidulafungin (Ekinokandinler)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["kaspofungin", "mikafungin", "anidulafungin", "ekinokandin", "1 3 beta d glukan sentaz", "hucre duvari inhibisyonu", "azole direncli kandida kandidemi", "invaziv aspergilloz kurtarma"]),
        ("Terbinafin", ["Tıbbi Farmakoloji", "Dermatoloji"], ["terbinafin", "lamisil", "skualen epoksidaz inhibisyonu", "allilamin", "onikomikoz tinea ungium tirnak mantari", "tinea pedis korporis"]),
        ("Flusitozin (5-FC)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["flusitozin", "5 fc", "sitozin deaminaz 5 fu donusumu", "rna ve dna sentez inhibisyonu", "kriptokok menenjiti amfoterisin b ile kombine", "kemik iligi supresyonu pansitopeni"]),
        ("Nistatin", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["nistatin", "mikostatin", "lokal polien", "oral pamukcuk kandidiyazis calkala yut", "sistemik emilmez toksiktir"])
    ]
    for name, discs, terms in antifungals:
        items.append((name, discs, terms))

    # Antiviraller
    antivirals = [
        ("Asiklovir & Valasiklovir", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["asiklovir", "valasiklovir", "timidin kinaz monofosfat", "dna polimeraz zincir sonlandirici", "hsv 1 hsv 2 vzv zona su cicegi", "herpes ensefaliti iv acil", "kristalize nefropati hidrasyon"]),
        ("Gansiklovir & Valgansiklovir", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["gansiklovir", "valgansiklovir", "ul97 fosfotransferaz cmv", "cmv retiniti koli transplant enfeksiyonu", "miyelosupresyon notropeni agir"]),
        ("Foskarnet", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["foskarnet", "piroposfat analoğu timidin kinaz gerektirmez", "asiklovir direncli hsv gansiklovir direncli cmv", "agir nefrotoksisite hipokalsemi hipomagnezemi elektrolit dengesizligi"]),
        ("Sidofovir", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["sidofovir", "sitozin monofosfat analoğu viral dna polimeraz", "cmv retiniti jc virus pml", "probenesid ile birlikte nefrotoksisiteyi onlemek icin"]),
        ("Oseltamivir & Zanamivir (Nöraminidaz İnhibitörleri)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["oseltamivir", "tamiflu", "zanamivir", "noraminidaz inhibitoru", "influenza a ve b viryon salinimi engeli", "ilk 48 saatte baslanmali"]),
        ("Baloksavir Marboksil", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["baloksavir marboksil", "cap dependent endonukleaz inhibitoru", "influenza tek doz oral tedavi"]),
        ("Remdesivir", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["remdesivir", "veklury", "rna bagimli rna polimeraz rdrp", "covid 19 sars cov 2", "ebola"]),
        ("Nirmatrelvir-Ritonavir (Paxlovid)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["paxlovid", "nirmatrelvir", "mpro 3cl proteaz inhibitoru sars cov 2", "ritonavir farmakokinetik guclendirici cyp3a4"]),
        ("Sofosbuvir & Ledipasvir (Direkt Etkili Hepatit C İlaçları)", ["Tıbbi Farmakoloji", "Gastroenteroloji", "Enfeksiyon Hastalıkları"], ["sofosbuvir", "ledipasvir", "harvoni", "ns5b rna polimeraz ns5a replikasyon kompleksi", "kronik hepatit c tam kur kuratif tedavi"]),
        ("Tenofovir & Entekavir (Hepatit B ve HIV Nükleotid/Nükleozidleri)", ["Tıbbi Farmakoloji", "Gastroenteroloji", "Enfeksiyon Hastalıkları"], ["tenofovir disoproksil", "tenofovir alafenamid", "entekavir", "hbv ters transkriptaz", "kronik hepatit b tedavisi", "fanconi sendromu bobrek osteomalazi tdf"]),
        ("Dolutegravir & Biktegravir (HIV İntegraz İnhibitörleri / INSTI)", ["Tıbbi Farmakoloji", "Enfeksiyon Hastalıkları"], ["dolutegravir", "biktegravir", "raltegravir", "insti integraz zincir transfer inhibitoru", "hiv art birinci basamak", "kilo artisi yuksek genetik bariyer"])
    ]
    for name, discs, terms in antivirals:
        items.append((name, discs, terms))

    # Kardiyovasküler İlaçlar
    cvs = [
        ("Enalapril, Ramipril & Kaptopril (ACE İnhibitörleri)", ["Tıbbi Farmakoloji", "Kardiyoloji", "Nefroloji"], ["ace inhibitoru", "enalapril", "ramipril", "kaptopril", "lizinopril", "anjiyotensin donusturucu enzim", "bradikinin birikimi", "kuru oksuruk", "anjiyoodem", "hiperkalemi", "diyabetik nefropatide proteinuriyi azaltir", "gebelikte kontrendike teratojen"]),
        ("Losartan, Valsartan & Kandesartan (ARB'ler)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["losartan", "valsartan", "kandesartan", "irbesartan", "at1 reseptor blokoru", "angiotensin reseptor blokoru", "oksuruk yapmaz bradikinin etkilemez", "kalp yetmezligi hipertansiyon"]),
        ("Amlodipin & Nifedipin (Dihidropiridin KKB)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["amlodipin", "nifedipin", "dihidropiridin kalsiyum kanal blokoru", "l tipi voltaj kapili kalsiyum kanali damar secici", "periferik pretibiyal odem vazodilatasyon", "refleks tasikardi nifedipin", "hipertansiyon raynaud"]),
        ("Verapamil & Diltiazem (Non-Dihidropiridin KKB)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["verapamil", "diltiazem", "non dihidropiridin kkb", "kardiyak secici l tipi kalsiyum", "negatif inotrop kronotrop dromotrop", "av dugum iletisini yavaslatir", "kabizlik konstipasyon verapamil", "kalp yetmezliginde beta blokerle tehlikeli blok"]),
        ("Metoprolol & Atenolol (Kardiyoselektif Beta-1 Blokerler)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["metoprolol", "atenolol", "bisoprolol", "nebivolol", "beta 1 selektif bloker", "kalp hizi kontraktilite renin azalmasi", "astimli hastada daha guvenli", "iskemik kalp hastaligi mi sonrasi"]),
        ("Propranolol (Non-Selektif Beta Bloker)", ["Tıbbi Farmakoloji", "Kardiyoloji", "Nöroloji"], ["propranolol", "non selektif beta bloker beta 1 ve 2", "astimda bronkospazm kontrendike", "esansiyel tremor", "tirotoksikoz tiroid firtinasi semptom kontrolu", "migren profilaksisi", "portal hipertansiyon varis kanama profilaksisi"]),
        ("Karvedilol & Labetalol (Alfa ve Beta Blokerler)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["karvedilol", "labetalol", "alfa 1 ve beta bloker", "periferik vazodilatasyon antioksidan", "kalp yetmezligi mortaliteyi azaltir karvedilol", "hipertansif kriz feokromositoma labetalol", "gebelik hipertansiyonu labetalol"]),
        ("Furosemid & Torsemid (Kıvrım / Loop Diüretikleri)", ["Tıbbi Farmakoloji", "Kardiyoloji", "Nefroloji"], ["furosemid", "lasix", "torsemid", "bumetanid", "henle kulpu cikan kalin kol", "nkcc2 na k 2cl kotransportoru", "en guclu diuretik", "akut pulmoner odem", "hipokalemi hipokalsemi hipomagnezemi hipovolemi", "ototoksisite hiperurisemi"]),
        ("Hidroklorotiyazid & Klortalidon (Tiyazid Diüretikleri)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["hidroklorotiyazid", "klortalidon", "indapamid", "distal kivrintili tubul", "nacl kotransportoru", "hiperkalsemi kalsiyum tutar", "hipokalemi hiponatremi hiperurisemi hiperglisemi", "osteoporozda ve kalsiyum tasinda tercih"]),
        ("Spironolakton & Eplerenon (Aldosteron Reseptör Antagonistleri)", ["Tıbbi Farmakoloji", "Kardiyoloji", "Endokrinoloji"], ["spironolakton", "aldacton", "eplerenon", "kortikal toplayici kanal aldosteron mr antagonisti", "potasyum tutucu diuretik", "hiperkalemi", "jinekomasti spironolakton selektif degil", "eplerenon selektif jinekomasti yapmaz", "kalp yetmezliginde mortalite azalmasi", "siroz asiti"]),
        ("Digoksin (Kardiyak Glikozid)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["digoksin", "na k atpaz pompasi inhibisyonu", "intrasellular sodyum ve kalsiyum artisi", "pozitif inotrop negatif kronotrop", "af kontrolu kalp yetmezligi semptom", "sari yesil gorme ksantopsi bulanti kusma aritmi", "hipokalemi toksisiteyi artirir", "digifab antidot"]),
        ("Sakubitril-Valsartan (ARNI)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["sakubitril", "valsartan", "entresto", "arni", "neprilisin inhibitoru", "bnp natriuretik peptid yikimini onler", "dusuk ejeksiyon fraksiyonlu kalp yetmezligi hfref mortalite azalmasi", "acei ile birlikte verilmez anjiyoodem riski en az 36 saat ara"]),
        ("İvabradin (Funny Akım / If İnhibitörü)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["ivabradin", "funny kanal funny akim if inhibitoru", "sinoatriyal dugum secici", "sadece kalp hizini yavaslatir inotrop etki yok", "gorsel parlama fosfen", "sinus ritminde kalp hizi 70 ustu kalp yetmezligi"]),
        ("Nitrogliserin & İzosorbid Mononitrat (Organik Nitratlar)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["nitrogliserin", "izosorbid dinitrat", "izosorbid mononitrat", "nitrik oksit salinimi cgmp artisi", "venodilatasyon on yuk preload azalmasi", "anjina pektoris akut ve profilaksi", "zonklayici bas agrisi yuzde kizarma", "tolerans pazartesi hastaligi", "sildenafil fosfodiesteraz 5 ile olumcul hipotansiyon"]),
        ("Amiodaron (Sınıf 3 Antiaritmik)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["amiodaron", "cordarone", "sinif 3 antiaritmik potasyum kanal blokoru", "aksiyon potansiyeli ve refrakter periyot uzamasi", "iyot icerir tiroid toksisitesi hipo hiper tiroidi", "pulmoner fibrozis kornea verticillata mavi gri cilt", "en etkili genis spektrumlu antiaritmik vt af"]),
        ("Atorvastatin & Rozuvastatin (HMG-KoA Redüktaz İnhibitörleri)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["statin", "atorvastatin", "rozuvastatin", "simvastatin", "hmg koa reduktaz inhibitoru hiz kisitlayici basamak", "hepatik ldl reseptor artisi ldl dusmesi", "miyopati rabdomiyoliz kreatin kinaz yuksekligi", "hepatotoksisite karaciger enzim takibi"]),
        ("Fenofibrat & Gemfibrozil (PPAR-Alfa Agonistleri / Fibratlar)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["fenofibrat", "gemfibrozil", "ppar alfa agonisti lipoprotein lipaz aktivasyonu", "trigliserit dusurucu hipertrigliseridemi", "akut pankreatit onleme", "statinle kombine edilirse miyopati riski artar"]),
        ("Ezetimib (NPC1L1 Kolesterol Emilim İnhibitörü)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["ezetimib", "npc1l1 tasiyici inhibitoru", "barsaktan kolesterol emilimini bloke eder", "statin yanina ek ldl dusurucu"]),
        ("Evolokumab & Alirokumab (PCSK9 İnhibitörleri)", ["Tıbbi Farmakoloji", "Kardiyoloji"], ["evolokumab", "alirokumab", "pcsk9 monoklonal antikoru", "ldl reseptor yikimini onler", "en guclu ldl dusurucu ailesel hiperkolesterolemi"]),
        ("Sodyum Nitroprussid & Hidralazin", ["Tıbbi Farmakoloji", "Kardiyoloji", "Acil Tıp"], ["sodyum nitroprussid", "hidralazin", "direkt damar genisletici arteriyol ve ven", "hipertansif acil acil kriz", "siyanur tiyosiyanat toksisitesi nitroprussid", "lupus benzeri sendrom yavas asetilleyicilerde hidralazin"]),
        ("Klonidin & Metildopa (Santral Alfa-2 Agonistleri)", ["Tıbbi Farmakoloji", "Kardiyoloji", "Kadın Hastalıkları ve Doğum"], ["klonidin", "metildopa", "santral alfa 2 adrenerjik agonist", "sempatik desariji azaltir", "gebelik hipertansiyonunda metildopa guvenli", "coombs pozitif otoimmun hemolitik anemi metildopa", "tedavi birden kesilirse rebound hipertansif kriz klonidin"])
    ]
    for name, discs, terms in cvs:
        items.append((name, discs, terms))

    # SSS ve Psikiyatri İlaçları
    cns = [
        ("Diazepam, Midazolam & Lorazepam (Benzodiazepinler)", ["Tıbbi Farmakoloji", "Psikiyatri", "Nöroloji", "Anesteziyoloji ve Reanimasyon"], ["benzodiazepin", "diazepam", "midazolam", "lorazepam", "alprazolam", "gaba a reseptoru klor kanal frekansi artisi", "sedasyon anksiyoliz antikonvulzan", "status epileptikus acil lorazepam diazepam", "bagimlilik tolerans solunum depresyonu", "flumazenil antidot"]),
        ("Fenobarbital & Tiopental (Barbitüratlar)", ["Tıbbi Farmakoloji", "Nöroloji", "Anesteziyoloji ve Reanimasyon"], ["barbiturat", "fenobarbital", "tiopental", "gaba a klor kanal acik kalma suresi artisi", "agir solunum ve dolasim depresyonu", "anestezi induksiyonu tiopental yeniden dagilim", "neonatal nobetler fenobarbital"]),
        ("Zolpidem & Zaleplon (Z-İlaçları)", ["Tıbbi Farmakoloji", "Psikiyatri"], ["zolpidem", "zaleplon", "zopiklon", "bz1 omega 1 secici gaba a", "uykuya dalma insomni", "antikonvulzan ve kas gevsetici etkisi zayiftir", "flumazenil ile geri dondurulebilir"]),
        ("Fenitoin (Voltaj Kapılı Sodyum Kanal Blokeri)", ["Tıbbi Farmakoloji", "Nöroloji"], ["fenitoin", "epantoin", "voltaj kapili na kanal inaktivasyon uzamasi", "sifir derece kinetigi mikailis menten", "gingival hiperplazi dis eti buyumesi", "hirsutizm ataksi nistagmus megaloblastik anemi", "fetal hidantoin sendromu teratojenite"]),
        ("Karbamazepin & Okskarbazepin", ["Tıbbi Farmakoloji", "Nöroloji", "Psikiyatri"], ["karbamazepin", "tegretol", "okskarbazepin", "voltaj kapili sodyum kanal blokoru", "trigeminal nevralji ilk tercih", "fokal nobetler", "cyp450 otoinduksiyonu", "agranulositoz aplastik anemi", "siadh hiponatremi", "stevens johnson sendromu hla b 1502"]),
        ("Valproik Asit / Sodyum Valproat", ["Tıbbi Farmakoloji", "Nöroloji", "Psikiyatri"], ["valproik asit", "depakin", "genis spektrumlu antiepileptik na t tipi ca gaba artisi", "jeneralize tonik klonik miyoklonik absans", "bipolar bozukluk", "hepatotoksisite fulminan", "pankreatit", "kilo artisi sac dokulmesi", "teratojen noral tup defekti spina bifida"]),
        ("Etosüksimid (T-Tipi Kalsiyum Kanal Blokeri)", ["Tıbbi Farmakoloji", "Nöroloji", "Pediatri"], ["etosuksimid", "zarontin", "t tipi t kalsiyum kanallari talamus", "saf absans nobet ilk tercih", "dalgali 3 hz diken dalga ekg", "baskaca nobet tiplerinde etkisizdir"]),
        ("Levetirasetam (SV2A Ligandı)", ["Tıbbi Farmakoloji", "Nöroloji"], ["levetirasetam", "keppra", "sv2a sinaptik vezikul proteini", "ilac etkilesimi en az antiepileptik", "davranis degisiklikleri irritabilite psikoz"]),
        ("Lamotrijin (Na Kanalı & Glutamat İnhibitörü)", ["Tıbbi Farmakoloji", "Nöroloji", "Psikiyatri"], ["lamotrijin", "lamictal", "voltaj kapili na blokaji glutamat salinimi azalmasi", "gebelikte en guvenli kabul edilen antiepileptik", "stevens johnson sendromu agir dokuntu yavas titrasyon"]),
        ("Topiramat (Çok Mekanizmalı Antiepileptik)", ["Tıbbi Farmakoloji", "Nöroloji"], ["topiramat", "topamax", "na kanal blokaji ampa kainat antagonisti karbonik anhidraz", "kilo kaybi zayiflama", "bobrek tasi nefrolitiyazis", "glokom oligohidrozis", "kelime bulma guclugu bilissel yavaslama"]),
        ("Levodopa-Karbidopa (Dopamin Replasmanı)", ["Tıbbi Farmakoloji", "Nöroloji"], ["levodopa", "karbidopa", "dopamin prekursoru l dopa kan beyin bariyerini gecer", "dopa dekarboksilaz inhibitoru karbidopa periferik yikimi onler", "parkinson hastaligi altin standart", "diskinezi on off fenomeni asiri motor dalgalanma", "halusinasyonlar bulanti"]),
        ("Pramipeksol & Ropinirol (Dopamin Reseptör Agonistleri)", ["Tıbbi Farmakoloji", "Nöroloji"], ["pramipeksol", "ropinirol", "d2 d3 dopamin agonisti non ergot", "huzursuz bacaklar sendromu rls", "genc parkinson hastasi", "durtu kontrol bozuklugu kumar hipersekssualite", "ani uyku ataklari"]),
        ("Selejilin & Rasajilin (MAO-B İnhibitörleri)", ["Tıbbi Farmakoloji", "Nöroloji"], ["selejilin", "rasajilin", "mao b secici geri donussuz inhibitor", "santral dopamin yikimini onler", "parkinson erken donem", "tiramin peynir reaksiyonu mao a ya gore cok dusuk"]),
        ("Biperiden & Triheksifenidil (Santral Antikolinerjikler)", ["Tıbbi Farmakoloji", "Nöroloji", "Psikiyatri"], ["biperiden", "akineton", "triheksifenidil", "santral muskarinik reseptor blokoru", "parkinson tremoru", "antipsikotik ilaclarin yaptigi akut distoni parkinsonizm tedavisi", "agiz kurulugu idrar retansiyonu glokom"]),
        ("Haloperidol & Klorpromazin (Tipik / 1. Kuşak Antipsikotikler)", ["Tıbbi Farmakoloji", "Psikiyatri"], ["haloperidol", "klorpromazin", "d2 reseptor antagonisti guclu", "ekstrapiramidal yan etkiler eps distoni parkinsonizm akatizi tardif diskinezi", "hiperprolaktinemi galaktore jinekomasti amenore", "noroleptik malign sendrom nms", "qt uzamasi torsades de pointes"]),
        ("Klozapin (Tedaviye Dirençli Şizofreni)", ["Tıbbi Farmakoloji", "Psikiyatri"], ["klozapin", "leponex", "atipik 2 kusak antipsikotik d4 5ht2a", "ekstrapiramidal yan etki yok denecek kadar az", "agranulositoz duzenli tam kan sayimi zorunlu", "miyokardit nobet esigini dusurur agir sedasyon kilo alimi hipersalivasyon"]),
        ("Olanzapin & Risperidon (Atipik Antipsikotikler)", ["Tıbbi Farmakoloji", "Psikiyatri"], ["olanzapin", "risperidon", "5ht2a ve d2 blokoru", "olanzapin agir kilo alimi metabolik sendrom diyabet", "risperidon hiperprolaktinemi eps riski yuksek atipik"]),
        ("Aripiprazol (Dopamin Parsiyel Agonisti)", ["Tıbbi Farmakoloji", "Psikiyatri"], ["aripiprazol", "abilify", "d2 parsiyel agonisti 5ht1a parsiyel agonisti 5ht2a antagonisti", "dopamin stabilizatoru", "kilo aldirmaz sedasyon az akatizi yapabilir"]),
        ("Fluoksetin, Sertralin & Essitalopram (SSRI)", ["Tıbbi Farmakoloji", "Psikiyatri"], ["ssri", "fluoksetin", "sertralin", "paroksetin", "sitalopram", "essitalopram", "secici serotonin geri alim inhibitoru sert", "depresyon anksiyete okb panik ilk tercih", "cinsel disfonksiyon libido kaybi anorgazmi", "gis bulanti diyare kilo degisiklikleri", "serotonin sendromu"]),
        ("Venlafaksin & Duloksetin (SNRI)", ["Tıbbi Farmakoloji", "Psikiyatri", "Nöroloji"], ["snri", "venlafaksin", "duloksetin", "serotonin ve noradrenalin geri alim inhibitoru sert ve net", "diyabetik periferik noropatik agri duloksetin", "fibromiyalji", "kan basinci artisi hipertansiyon venlafaksin yuksek doz"]),
        ("Amitriptilin & İmipramin (Trisiklik Antidepresanlar / TCA)", ["Tıbbi Farmakoloji", "Psikiyatri", "Nöroloji"], ["amitriptilin", "laroxyl", "imipramin", "klomipramin", "trisiklik antidepresan tca", "serotonin ve noradrenalin geri alim blokaji + antikolinerjik + antihistaminik + alfa 1 blokaj", "3c kardiyotoksisite konvulziyon koma", "qrs genislemesi aritmiler sodyum bikarbonat antidot", "enurezis nokturna imipramin", "okb klomipramin"]),
        ("Bupropion (Atipik Antidepresan / Sigara Bırakma)", ["Tıbbi Farmakoloji", "Psikiyatri"], ["bupropion", "wellbutrin", "zyban", "noradrenalin ve dopamin geri alim inhibitoru ndri", "cinsel yan etki yapmaz kilo aldirmaz", "sigara birakma tedavisi", "nobet esigini dusurur bulimiya anoreksiyada kontrendike"]),
        ("Lityum Karbonat (Bipolar Bozukluk Duygudurum Dengeleyici)", ["Tıbbi Farmakoloji", "Psikiyatri"], ["lityum", "inositol monofosfataz impaz inhibisyonu pip2 yolu", "bipolar afektif bozukluk mani profilaksi", "dar terapötik aralik kan duzeyi takibi 0 6 1 2", "nefrojenik diabetes insipidus idrar tutamama", "hipotiroidizm guatr", "ebstein anomalisi teratojenite trikuspit kapak", "tiyazid ve nsaid klerensi azaltir toksisite artar"])
    ]
    for name, discs, terms in cns:
        items.append((name, discs, terms))

    return items
